### ISSUE TITLE
[Proposal] Support gettext 

### ISSUE THREAD

**Issue by avgerin0s** [change/linguist#2]
Just a proposal that, imho, would be very nice.

**Comment by michaelbaudino** [comment]
I definitely don't think gettext would be a good idea, here.

Mixing keys and values (more precisely: using some of the values as keys) is a terrible idea for:
- **usability** because one English sentence used in multiple places often needs many different translations in other languages due to context (think about declension) or grammar (think about pluralization)
- **maintainability** because you would need to change your codebase when you change a minor wording in the source language
- **compatibility** because it's not trivial to convert Gettext data to an in-code object, _e.g._ a `Map` (keyword lists are also a bad idea because of key redundancy, IMHO)

A key-indexed tree hierarchy (as provided by JSON, YAML or TOML) is a far better way to go, IMHO. And just in case anyone cares, I'd go for JSON as existing YAML parsers have recurrent security and compatibility issues.

**Comment by barrieloydall** [comment]
closing old dormant issues
